### ISSUE TITLE
404 - Link

### ISSUE THREAD

**Issue by Triloworld** [TK-54-4B/ProjectSkills#3]
Miejsce: 
https://tk-54-4b.github.io/ProjectSkills/

Jaki link jest 404:
https://tk-54-4b.github.io/ProjectSkills/ShoppingCartSlideMenu

Jaki plik: 
https://github.com/TK-54-4B/ProjectSkills/blob/51e48511742ddc7897276549c27e6124b4994b1e/index.html

Należy poprawić link bo 404 jest

**Comment by TK-54-4B** [comment]
done, brakowało mojego indeksu "14_3"

**Comment by Triloworld** [comment]
Zweryfikowane i działa :D
